---
title: "Lab 02 - Global plastic waste"
author: "Juan's Kingdom: Lim Zhen Yang, Mingshi Yue, zimo wang and Yunhao Wang"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message = FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
```


## Load & join data sets

```{r load-data, message = FALSE}
# Member 1
data1 <- read_csv("data/mismanaged-plastic-waste-per-capita.csv")



# Member 2 write code to load File 2 data here:
data2 <- read_csv2("data/per-capita-ocean-plastic-waste.txt")

# Member 3 write code to load File 3 data here:
data3 <- read_tsv("data/UN_country_population.tsv")


# Member 4 write code to load File 4 data here:
data4 <- read_excel("data/UN_country_region.xlsx")


```



```{r join-data, message = FALSE}
# Member 1
plastic_data_all <- data1



# Member 2 write code to join your data to 'plastic_data_all':

plastic_data_all <- data2 %>%
  select(-name) %>%
  left_join(plastic_data_all, by = "code")


# Member 3 write code to join your data to 'plastic_data_all':
plastic_data_all <- data3 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


# Member 4 write code to join your data to 'plastic_data_all':
plastic_data_all <- data4 %>%
  select(-name) %>%
  right_join(plastic_data_all, by = "code")


```


```{r print-data, message = FALSE}
plastic_data_all %>% head(n = 10)



```



## Exercises

### Ex 1.

```{r Ex1, message = FALSE}
# Write your code here to answer exercise 1

data2%>%
  left_join(data4,by = "name")%>%
  count(region)

```



### Ex 2.

```{r Ex2, message = FALSE}
# Write your code here to answer exercise 2



```


### Ex 3.

```{r Ex3, message = FALSE}
# Write your code here to answer exercise 3



```


### Ex 4.

```{r Ex4, message = FALSE}
# Write your code here to answer exercise 4



```
